name: rest-compat
on:
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  api-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: go-build-bin-${{ hashFiles('**/go.mod') }}
          restore-keys: go-build-bin-
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Build openapi.json
        if: hashFiles('./wiki/openapi.json') != ''
        run: |
          make build
          ./bin/* -openapi > openapi.json
          cat ./openapi.json
      - name: Check API changes
        if: hashFiles('./wiki/openapi.json') != ''
        uses: docker://openapitools/openapi-diff
        with:
          args: ./wiki/openapi.json ./openapi.json --markdown api-changes.md
      - name: Read report
        if: hashFiles('./wiki/openapi.json') != ''
        id: report
        run: |
          OUTPUT=$(cat api-changes.md)
          echo "${OUTPUT}"
          OUTPUT="${OUTPUT//$'\n'/%0A}"
          echo "::set-output name=diff::$OUTPUT"
      - name: Update Comment
        if: hashFiles('./wiki/openapi.json') != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: rest-compat
          message: |
            ### REST API Changes
            <details><summary>Changes report</summary>

            ${{ steps.report.outputs.diff }}

            </details>

